### ISSUE TITLE
Duplicated Lines

### ISSUE THREAD

**Issue by aminone** [aliab/website-in-webview#1]
سلام و ممنون برای کارای خوبت
فکر می‌کنم در اکتیویتی اصلی‌ات [این خط](https://github.com/aliab/website-in-webview/blob/master/src/info/abdolahi/showtheweb/MainActivity.java#L52) و خط بعدیش داپلیکیت شده باشه

موفق باشی

**Comment by aliab** [comment]
@aminone salam, are, merc az komaketun, vaghty shab ta sobh adam kar mikone, az in moshkelat pish miad,
code ha ro update kardam, chand ta feature dg ham ezafe kardam ;)
